### ISSUE TITLE
0.5.3 Crash on Launch Fabric

### ISSUE THREAD

**Issue by klinbee** [SettingDust/RegistryBlocker#6]
For some reason, whenever I try to use this mod on version 0.5.3, it gives me this crash even though I have the Fabric Language Kotlin mod depndency. This doesn't occur on version 0.3.0.

Mods/Loaders Used: (I've also tried Minecraft 1.21.1 Fabric with a similar set-up)
Minecraft 1.20.1
Fabric Loader 0.16.14
Fabric API 0.92.6+1.20.1
RegistryBlocker 0.5.3
Fabric Language Kotlin 1.13.6+kotlin.2.2.20
```
org.quiltmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'registry-blocker' at 'settingdust.registryblocker.EntrypointKt::init'!
	at org.quiltmc.loader.impl.QuiltLoaderImpl.invokePreLaunch(QuiltLoaderImpl.java:1244)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:178)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:79)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'registry-blocker' at 'settingdust.registryblocker.EntrypointKt::init'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.invokePreLaunch(QuiltLoaderImpl.java:1242)
	... 6 more
Caused by: org.quiltmc.loader.impl.entrypoint.QuiltEntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'registry-blocker'
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:241)
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:73)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: org/quiltmc/qkl/library/serialization/options/CodecOptionsBuilder
	at settingdust.registryblocker.EntrypointKt.<clinit>(Entrypoint.kt:37)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at net.fabricmc.language.kotlin.KotlinAdapter.create(KotlinAdapter.kt:40)
	at net.fabricmc.loader.api.LanguageAdapter.create(LanguageAdapter.java:124)
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:123)
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:239)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.quiltmc.qkl.library.serialization.options.CodecOptionsBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:204)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:176)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:243)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 20 more
	```

**Comment by SettingDust** [comment]
in 0.3.0 it's nested. But for work with 1.21 the kinecraft serialization isn't nested now xdd

**Comment by SettingDust** [comment]
oh. I marked the wrong slug :( 

<img width="281" height="127" alt="Image" src="https://github.com/user-attachments/assets/8f6b7bdc-9098-4b92-8023-34bd450956d3" />

**Comment by klinbee** [comment]
Ahhh! Small error

**Comment by SettingDust** [comment]
isn't depends on kinecraft serialization in 0.6.0
